### ISSUE TITLE
mAP of YOLOV3 on VOC

### ISSUE THREAD

**Issue by Hello526** [sonal-bansal/Yolo-v3#1]
Hi,
Do you get the mAP of YOLOV3 on the VOC dataset?

**Comment by sonal-bansal** [comment]
Hi @Hello526 ,

mAP is basically the mean of the average-precisions of all the classes(which is = TP/(TP+FP)).It is the average of the maximum precisions at different recall values.
IOU(measures overlap between 2 regions) is used for identifying true positive and false positive, and i kept the iou threshold as 0.5.

To understand the concept of mAP more ,refer this link:
https://medium.com/@jonathan_hui/map-mean-average-precision-for-object-detection-45c121a31173

**Comment by Hello526** [comment]
Thanks a lot, I would also like to ask, what is the mAP obtained when you use YOLOV3 to test on the PASCAL VOC2007 test set?

**Comment by Hello526** [comment]
I only got 63.2% of mAP, so I think something went wrong.

**Comment by sonal-bansal** [comment]
Hi @Hello526 ,

Actually I've tested on 2012VOC test set, but i dont think it should that low, if you could please send me how you are calculating mAP, and what are the no. of epochs.
